### ISSUE TITLE
Use GitHub Release to publish, rather than pushing binaries to the repo

### ISSUE THREAD

**Issue by zymelaii** [MakiseKurisu-Labmem004/DownTerraria-Roguelike-Game#1]
Up 可以把构建的程序发布到 GitHub Release 里，另外动态链接的话需要把 SDL 那几个 dll 打包下， gcc 的 libstdc++ 或许也需要。

PS: 4k 单文件最后还能写到这样清晰的程序真滴是太 C 啦 😆

**Comment by MakiseKurisu-Labmem004** [comment]
谢谢提醒,可是我不会动态链接呜呜呜,只能先加上exe了

**Comment by MakiseKurisu-Labmem004** [comment]
我不太会诶 不过谢谢提醒!
